import Layout from '@/components/Layout';
import Head from 'next/head';
import AnimatedText from '@/components/AnimatedText';
import Link from 'next/link';
import { LinkArrow } from '@/components/Icons';

export default function Home() {
  return (
    <>
      <Head>
      <title>SoundSculpt | Home Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className='flex items-center text-dark w-full min-h-screen'>
        <Layout className='pt-0'>
          <div className='flex items-center justify-between w-full'>
            <div className='w-1/2'>
              <img src='/images/arts/home.png' alt='' className='w-full h-auto' />
            </div>
            <div className='w-1/2 flex flex-col items-center self-center'>
              <AnimatedText text="Crafting your audio experience with the power of AI." className='!text-6xl !text-left' />
              <p className='my-4 text-base font-medium'>
              Welcome to SoundSculpt, the future of personalized audio. Leveraging advanced AI technology, we transform your music to match your unique style. Upload, describe, and let us craft your perfect sound!
              </p>
              <div className='flex items-center self-start mt-2'>
                <Link 
                  href='/upload' 
                  className='flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark'
                >Explore <LinkArrow className={'w-6 ml-1'} />
                </Link>
                <Link 
                  href='mailto:giabaonguyen.workspace@gmail.com' 
                  target={"_blank"}
                  className='ml-4 flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark'
                >Contact</Link>
              </div>
            </div>
          </div>
        </Layout>

        {/* <div className='absolute right-8 bottom-8 inline-block w-24'>
          <Image src={lightBulb} alt='' className='w-full h-auto' />
        </div> */}
      </main>
    </>
  );
}
